POST http://localhost:4000/api/signup
Content-Type: application/json

{
  "name": "sandy",
  "email": "sandy@example.com",
  "password": "sandy@1",
  "role":1
}

###

POST http://localhost:4000/api/signin
Content-Type: application/json

{
  "name": "sandy",
  "email": "sandy@example.com",
  "password": "sandy@1"
}

###
GET http://localhost:4000/api/signout


###

GET http://localhost:4000/api/secret/5fc4dea17e2bd59a2c201ba2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmM0ZGVhMTdlMmJkNTlhMmMyMDFiYTIiLCJpYXQiOjE2MDY3Mzc1OTB9.FAvJ5e1o3B6GMbOx9C7wcH9hSkjweqCTZARtn-nhbr0


###

POST http://localhost:4000/api/category/create/5fc4dea17e2bd59a2c201ba2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmM0ZGVhMTdlMmJkNTlhMmMyMDFiYTIiLCJpYXQiOjE2MDY3Mzc1OTB9.FAvJ5e1o3B6GMbOx9C7wcH9hSkjweqCTZARtn-nhbr0

{
  "name": "Nodejs essentials"
}


###

POST http://localhost:4000/api/product/create/5fc4dea17e2bd59a2c201ba2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmM0ZGVhMTdlMmJkNTlhMmMyMDFiYTIiLCJpYXQiOjE2MDY3Mzc1OTB9.FAvJ5e1o3B6GMbOx9C7wcH9hSkjweqCTZARtn-nhbr0

{
  "name": "Node Book",
  "description": "My first book on mern",
  "price": 20,
  "category": "5fc4df027e2bd59a2c201ba3",
  "shipping": false,
  "quantity": 100
}

###
GET http://localhost:4000/api/product/


###

DELETE http://localhost:4000/api/product/



